services:
  qcc74x-toolchain:
    build:
      context: .
      dockerfile: Dockerfile
    image: cubicattache/qcc74x-toolchain:latest
    volumes:
      - .:/workspace:rw
    working_dir: /workspace
    platform: linux/amd64
